.PONY: hello_world_c hello_world_cpp

APP=hello_world

hello_world_c:
	@echo "Building C code..."
	@gcc ${APP}.c -o ${APP}.out
	@echo "Executing C code..."
	@./${APP}.out

hello_world1_cpp:
	@echo "Building C++ code..."
	@g++ ${APP}2.cpp -o ${APP}.out
	@echo "Executing C++ code..."
	@./${APP}.out

hello_world2_cpp:
	@echo "Building C++ code..."
	@g++ ${APP}2.cpp -o ${APP}.out
	@echo "Executing C++ code..."
	@./${APP}.out
